version: '2.4'

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - NODE_ENV=NODE_ENV
    #command: npm run dev
    restart: always
    container_name: node_app
    ports:
      - "3000:3000"
      - "9229:9229"
      - "9230:9230"
    volumes:
      - .:/opt/node_app/app:delegated 
      - ./package.json:/opt/node_app/package.json
      - ./package-lock.json:/opt/node_app/package-lock.json
      - notused:/opt/node_app/app/node_modules
    environment:
      - NODE_ENV=NODE_ENV
volumes:
  notused: